import type { Property } from "@/lib/types"

export const demoProperties: Property[] = [
  {
    id: "demo-suva-2br",
    owner_id: "demo",
    title: "Modern 2-bedroom apartment in Suva",
    description: "A bright, fully tiled apartment close to the city, shops and public transport.",
    property_type: "Apartment",
    address: "Suva",
    city: "Suva",
    bedrooms: 2,
    bathrooms: 1,
    rent_amount: 1200,
    available_from: null,
    furnished: false,
    amenities: ["Car park", "Hot water"],
    images: ["/modern-apartment-suva.png"],
    contact_phone: "",
    whatsapp_phone: null,
    status: "approved",
    featured: true,
    verified: true,
    rejection_reason: null,
    created_at: "2026-07-01T00:00:00Z",
    profiles: { full_name: "Verified landlord", verified: true },
  },
  {
    id: "demo-nasinu-1br",
    owner_id: "demo",
    title: "Affordable 1-bedroom flat in Nasinu",
    description: "A practical home for a couple, with easy access to buses and nearby shops.",
    property_type: "Flat",
    address: "Nasinu",
    city: "Nasinu",
    bedrooms: 1,
    bathrooms: 1,
    rent_amount: 550,
    available_from: null,
    furnished: false,
    amenities: ["Tiled", "Public transport nearby"],
    images: ["/affordable-apartment-nasinu.png"],
    contact_phone: "",
    whatsapp_phone: null,
    status: "approved",
    featured: false,
    verified: false,
    rejection_reason: null,
    created_at: "2026-07-02T00:00:00Z",
    profiles: { full_name: "Property owner", verified: false },
  },
  {
    id: "demo-lautoka-house",
    owner_id: "demo",
    title: "Family house in Lautoka",
    description: "A spacious family home with a secure yard and separate parking.",
    property_type: "House",
    address: "Lautoka",
    city: "Lautoka",
    bedrooms: 3,
    bathrooms: 2,
    rent_amount: 1800,
    available_from: null,
    furnished: false,
    amenities: ["Secure yard", "Car park"],
    images: ["/lautoka-family-house.png"],
    contact_phone: "",
    whatsapp_phone: null,
    status: "approved",
    featured: false,
    verified: true,
    rejection_reason: null,
    created_at: "2026-07-03T00:00:00Z",
    profiles: { full_name: "Verified agent", verified: true },
  },
  {
    id: "demo-nadi-villa",
    owner_id: "demo",
    title: "Bright 3-bedroom home near Nadi",
    description: "A comfortable family home with generous living space and easy access to Nadi town.",
    property_type: "House",
    address: "Nadi",
    city: "Nadi",
    bedrooms: 3,
    bathrooms: 2,
    rent_amount: 1500,
    available_from: null,
    furnished: false,
    amenities: ["Car park", "Large living area"],
    images: ["/beachfront-villa-nadi.png"],
    contact_phone: "",
    whatsapp_phone: null,
    status: "approved",
    featured: true,
    verified: true,
    rejection_reason: null,
    created_at: "2026-07-04T00:00:00Z",
    profiles: { full_name: "Verified landlord", verified: true },
  },
]
